[workspace.package]
version = "0.2.0"
authors = ["RustPython Team"]
edition = "2021"
rust-version = "1.67.1"
description = "Python parser and its dependencies."
repository = "https://github.com/RustPython/Parser"
license = "MIT"
include = ["LICENSE", "Cargo.toml", "src/**/*.rs"]

[workspace]
resolver = "2"
members = [
    "ast", "core", "format", "literal", "parser", "parser-pyo3",
    "ruff_text_size", "ruff_source_location",
]

[workspace.dependencies]
rustpython-ast = { path = "ast", default-features = false }
rustpython-parser-core = { path = "core", features = [] }
rustpython-literal = { path = "literal" }
rustpython-format = { path = "format" }
rustpython-parser = { path = "parser" }

ahash = "0.7.6"
anyhow = "1.0.45"
cfg-if = "1.0"
insta = "1.14.0"
itertools = "0.10.3"
is-macro = "0.2.2"
log = "0.4.16"
num-complex = "0.4.0"
num-bigint = "0.4.3"
num-traits = "0.2"
pyo3 = { version = "0.18.3" }
rand = "0.8.5"
serde = "1.0"
static_assertions = "1.1"
once_cell = "1.17.1"
unicode_names2 = { version = "0.6.0", git = "https://github.com/youknowone/unicode_names2.git", rev = "4ce16aa85cbcdd9cc830410f1a72ef9a235f2fde" }

[profile.dev.package."*"]
opt-level = 3

[profile.bench]
lto = "thin"
codegen-units = 1
opt-level = 3

[profile.release]
lto = "thin"
